- name: Deploy single-node Kubernetes cluster
  hosts: master
  vars_files:
    - ../vars/main.yml
  roles:
    - role: common
    - role: containerd
    - role: kubernetes
    - role: init_cluster
    - role: cni_calico
