---
- name: Create cert-manager namespace
  kubernetes.core.k8s:
    api_version: v1
    kind: Namespace
    name: "{{ cert_manager_namespace }}"
    state: present

- name: Add cert-manager Helm repo
  community.kubernetes.helm_repository:
    name: jetstack
    repo_url: "{{ cert_manager_chart_repo }}"

- name: Install cert-manager via Helm
  community.kubernetes.helm:
    name: "{{ cert_manager_release_name }}"
    chart_ref: jetstack/{{ cert_manager_chart_name }}
    release_namespace: "{{ cert_manager_namespace }}"
    create_namespace: false
    values:                                   
      installCRDs: true                               
    wait: true
    update_repo_cache: true
    chart_version: "{{ cert_manager_chart_version }}"

- name: Create self-signed ClusterIssuer
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: cert-manager.io/v1
      kind: ClusterIssuer
      metadata:
        name: "{{ selfsigned_issuer_name }}"
      spec:
        selfSigned: {}
