cert_manager_namespace: cert-manager
cert_manager_release_name: cert-manager
cert_manager_chart_repo: https://charts.jetstack.io
cert_manager_chart_name: cert-manager
cert_manager_chart_version: "1.14.4"  

selfsigned_issuer_name: selfsigned-clusterissuer