rancher_namespace: cattle-system
rancher_release_name: rancher
rancher_chart_repo: https://releases.rancher.com/server-charts/stable
rancher_chart_name: rancher
rancher_chart_version: "2.11.3"  # Совместим с cert-manager и ingressClassName, TLS via certManager
rancher_hostname: rancher.local
rancher_replicas: 1
