---
- name: Create namespace for dashboards
  kubernetes.core.k8s:
    api_version: v1
    kind: Namespace
    name: "{{ rancher_namespace }}"
    state: present

- name: Add Rancher Helm repo
  community.kubernetes.helm_repository:
    name: rancher-stable
    repo_url: "{{ rancher_chart_repo }}"

- name: Install Rancher via Helm
  community.kubernetes.helm:
    name: "{{ rancher_release_name }}"
    chart_ref: rancher-stable/{{ rancher_chart_name }}
    release_namespace: "{{ rancher_namespace }}"
    create_namespace: false
    wait: true
    update_repo_cache: true
    chart_version: "{{ rancher_chart_version }}"
    values:
      hostname: "{{ rancher_hostname }}"
      replicas: "{{ rancher_replicas }}"
      ingress:
        enabled: true
        ingressClassName: nginx
        tls:
          source: certManager
